### ISSUE TITLE
ECONNREFUSED 127.0.0.1:4370 error

### ISSUE THREAD

**Issue by BannerBomb** [zackdevine/spotibot#1]
I keep getting
`{ Error: connect ECONNREFUSED 127.0.0.1:4370
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 4370 }`
when i run the run.bat file

**Comment by jaaiden** [comment]
Not sure what could have caused this. Do you have Spotify running prior to starting the bot?

**Comment by BannerBomb** [comment]
I had Spotify open when i ran it it said that same for if spotify is closed, people I guess been having that problem with node-spotify-webhelper as I googles the error and alot of the same came up like this
https://github.com/nadavbar/node-spotify-webhelper/issues/10 as subhackar said to use the changed port and http, which shows the changes [here](https://github.com/nadavbar/node-spotify-webhelper/issues/11)

**Comment by jaaiden** [comment]
In that case try updating the node modules within the spotibot folder by running `npm update` using your default terminal program where node is installed. Let me know if this works!

**Comment by BannerBomb** [comment]
no it didnt work, still says the same thing

**Comment by BannerBomb** [comment]
I was able to fix the error myself I used Webroot SecureAnywhere to view all the connections being made on my computer and went to the one being made by spotify.exe which is 127.0.0.1:4381, you have to update 2 things inside the `C:\Users\Owner\Desktop\spotibot-master\node_modules\node-spotify-webhelper\index.js` file which are, 

**BEFORE MODIFICATION**
**Line 15**: `var DEFAULT_PORT = 4370;`
**Line 158**: `return util.format("https://%s:%d%s", generateRandomLocalHostName(), localPort, url)`

**AFTER MODIFICATION**
**Line 15**: `var DEFAULT_PORT = 4381;`
**Line 158**: `return util.format("http://%s:%d%s", generateRandomLocalHostName(), localPort, url)`

cause if u try to access the TCP4 using https then it will unexpectedly close the port, so if u type it in as `127.0.0.1:4381` in your browser it will say `missing method` which means its open so u can use it in the script to connect to it I learned that spotify changes their port after awhile.

**Comment by jaaiden** [comment]
This is an issue with [node-spotify-webhelper](https://github.com/nadavbar/node-spotify-webhelper), closing the issue.
